-- Coop & Lidl stores seed SQL
-- Run this in Supabase SQL Editor

-- Batch 1
INSERT INTO stores (id, chain_id, external_id, name, address, city, profile) VALUES
('coop-598', 'coop', '598', 'Coop Krylbo', '', 'Krylbo', 'Coop'),
('coop-3788', 'coop', '3788', 'Coop Askersund', '', 'Askersund', 'Coop'),
('coop-3785', 'coop', '3785', 'Coop City Hallsberg', '', 'Hallsberg', 'Coop'),
('coop-3739', 'coop', '3739', 'Coop Tibro', '', 'Tibro', 'Coop'),
('coop-3742', 'coop', '3742', 'Coop Mariestad Marieforsleden', '', 'Mariestad', 'Coop'),
('coop-3562', 'coop', '3562', 'Coop Vara', '', 'Vara', 'Coop'),
('coop-3565', 'coop', '3565', 'Coop Borås Sjöbotorg', '', 'Borås', 'Coop'),
('coop-3566', 'coop', '3566', 'Coop Ulricehamn', '', 'Ulricehamn', 'Coop'),
('coop-3571', 'coop', '3571', 'Coop Uddevalla Göteborgsvägen', '', 'Uddevalla', 'Coop'),
('coop-3575', 'coop', '3575', 'Coop Göteborg Marklandsgatan', '', 'Göteborg', 'Coop'),
('coop-3578', 'coop', '3578', 'Coop Bohus', '', 'Bohus', 'Coop'),
('coop-3579', 'coop', '3579', 'Coop Mjörnbotorget', '', 'Gråbo', 'Coop'),
('coop-3881', 'coop', '3881', 'Coop Oxelösund', '', 'Oxelösund', 'Coop'),
('coop-3870', 'coop', '3870', 'Coop Bråddgatan', '', 'Norrköping', 'Coop'),
('coop-3630', 'coop', '3630', 'Coop Engelbrektsgatan Trelleborg', '', 'Trelleborg', 'Coop'),
('coop-3880', 'coop', '3880', 'Coop Vingåkersvägen Katrineholm', '', 'Katrineholm', 'Coop'),
('coop-3648', 'coop', '3648', 'Coop Slottsstaden', '', 'Malmö', 'Coop'),
('coop-3659', 'coop', '3659', 'Coop Värpinge Lund', '', 'Lund', 'Coop'),
('coop-3661', 'coop', '3661', 'Coop Bjuv', '', 'Bjuv', 'Coop'),
('coop-3667', 'coop', '3667', 'Coop Nybrovägen', '', 'Ängelholm', 'Coop'),
('coop-3811', 'coop', '3811', 'Coop Fyllinge', '', 'Halmstad', 'Coop'),
('coop-3678', 'coop', '3678', 'Coop Råtorp', '', 'Karlstad', 'Coop'),
('coop-3679', 'coop', '3679', 'Coop Strand', '', 'Karlstad', 'Coop'),
('coop-3864', 'coop', '3864', 'Coop Fiskaregatan Vimmerby', '', 'Vimmerby', 'Coop'),
('coop-3681', 'coop', '3681', 'Coop Folkparksvägen', '', 'Västervik', 'Coop'),
('coop-3682', 'coop', '3682', 'Coop Västervik Vapengränd', '', 'Västervik', 'Coop'),
('coop-3684', 'coop', '3684', 'Coop Östermalmshallen', '', 'Finspång', 'Coop'),
('coop-3687', 'coop', '3687', 'Coop Vaggeryd', '', 'Vaggeryd', 'Coop'),
('coop-3689', 'coop', '3689', 'Coop Hagaberg', '', 'Jönköping', 'Coop'),
('coop-3863', 'coop', '3863', 'Coop Åsavägen', '', 'Oskarshamn', 'Coop'),
('coop-3696', 'coop', '3696', 'Coop Funkabo', '', 'Kalmar', 'Coop'),
('coop-3697', 'coop', '3697', 'Coop Kalmar Sandåsgatan', '', 'Kalmar', 'Coop'),
('coop-3702', 'coop', '3702', 'Coop Nydalavägen', '', 'Växjö', 'Coop'),
('coop-3703', 'coop', '3703', 'Coop Nybro', '', 'Nybro', 'Coop'),
('coop-3704', 'coop', '3704', 'Coop Växjö Emil Lindells Väg', '', 'Växjö', 'Coop'),
('coop-3708', 'coop', '3708', 'Coop Västra Vallgatan', '', 'Varberg', 'Coop'),
('coop-3711', 'coop', '3711', 'Coop Värnamo Fredsgatan', '', 'Värnamo', 'Coop'),
('coop-3712', 'coop', '3712', 'Coop Gislaved', '', 'Gislaved', 'Coop'),
('coop-3723', 'coop', '3723', 'Coop Kallebäck', '', 'Göteborg', 'Coop'),
('coop-3724', 'coop', '3724', 'Coop Göteborg Andra Långgatan', '', 'Göteborg', 'Coop'),
('coop-3729', 'coop', '3729', 'Coop Svalöv', '', 'Svalöv', 'Coop'),
('coop-3716', 'coop', '3716', 'Coop Markaryd', '', 'Markaryd', 'Coop'),
('coop-3755', 'coop', '3755', 'Coop Bredden', '', 'Upplands Väsby', 'Coop'),
('coop-3761', 'coop', '3761', 'Coop Bredsand', '', 'Sundsvall', 'Coop'),
('coop-1231', 'coop', '1231', 'Stora Coop Kristinehamn', '', 'Kristinehamn', 'Coop'),
('coop-1437', 'coop', '1437', 'Stora Coop Ersboda', '', 'Umeå', 'Coop'),
('coop-1438', 'coop', '1438', 'Stora Coop Härnösand', '', 'Härnösand', 'Coop'),
('coop-631', 'coop', '631', 'Stora Coop Örnsköldsvik', '', 'Örnsköldsvik', 'Coop'),
('coop-1546', 'coop', '1546', 'Stora Coop Boden', '', 'Boden', 'Coop'),
('coop-1570', 'coop', '1570', 'Stora Coop Piteå', '', 'Piteå', 'Coop'),
('coop-2206', 'coop', '2206', 'Stora Coop Karlshamn', '', 'Karlshamn', 'Coop'),
('coop-1182', 'coop', '1182', 'Stora Coop Överby', '', 'Trollhättan', 'Coop'),
('coop-1930', 'coop', '1930', 'Stora Coop Östersund', '', 'Östersund', 'Coop'),
('coop-1958', 'coop', '1958', 'Stora Coop Vinsta', '', 'Vällingby', 'Coop'),
('coop-657', 'coop', '657', 'Stora Coop Bromma', '', 'Bromma', 'Coop'),
('coop-1929', 'coop', '1929', 'Stora Coop Norremark', '', 'Växjö', 'Coop'),
('coop-3225', 'coop', '3225', 'Stora Coop Visby', '', 'Visby', 'Coop'),
('coop-1344', 'coop', '1344', 'Stora Coop Valbo', '', 'Valbo', 'Coop'),
('coop-1551', 'coop', '1551', 'Stora Coop Storheden', '', 'Luleå', 'Coop'),
('coop-1938', 'coop', '1938', 'Stora Coop Sisjön', '', 'Askim', 'Coop'),
('coop-661', 'coop', '661', 'Stora Coop Skara', '', 'Skara', 'Coop'),
('coop-656', 'coop', '656', 'Stora Coop Backaplan', '', 'Göteborg', 'Coop'),
('coop-655', 'coop', '655', 'Stora Coop Bäckebol', '', 'Hisings Backa', 'Coop'),
('coop-3795', 'coop', '3795', 'Coop Forum Marieberg', '', 'Örebro', 'Coop'),
('coop-1436', 'coop', '1436', 'Stora Coop Sörböle', '', 'Skellefteå', 'Coop'),
('coop-1539', 'coop', '1539', 'Stora Coop Kiruna', '', 'Kiruna', 'Coop'),
('coop-2275', 'coop', '2275', 'Stora Coop Västberga', '', 'Hägersten', 'Coop'),
('coop-2677', 'coop', '2677', 'Stora Coop Varberg', '', 'Varberg', 'Coop'),
('coop-3853', 'coop', '3853', 'Stora Coop Stadion', '', 'Malmö', 'Coop'),
('coop-2246', 'coop', '2246', 'Stora Coop Häggvik', '', 'Sollentuna', 'Coop'),
('coop-28', 'coop', '28', 'Stora Coop Huddinge', '', 'Huddinge', 'Coop'),
('coop-1954', 'coop', '1954', 'Stora Coop Märsta', '', 'Märsta', 'Coop'),
('coop-676', 'coop', '676', 'Stora Coop Nolhaga Skövde', '', 'Skövde', 'Coop'),
('coop-2278', 'coop', '2278', 'Stora Coop Kungsbacka', '', 'Kungsbacka', 'Coop'),
('coop-2696', 'coop', '2696', 'Stora Coop Lund', '', 'Lund', 'Coop'),
('coop-1225', 'coop', '1225', 'Stora Coop Bergvik', '', 'Karlstad', 'Coop'),
('coop-1544', 'coop', '1544', 'Stora Coop Kalix', '', 'Kalix', 'Coop'),
('coop-3147', 'coop', '3147', 'Stora Coop Sundby Park', '', 'Sundbyberg', 'Coop'),
('coop-1839', 'coop', '1839', 'Stora Coop Hudiksvall', '', 'Hudiksvall', 'Coop'),
('coop-643', 'coop', '643', 'Stora Coop Boländerna', '', 'Uppsala', 'Coop'),
('coop-2703', 'coop', '2703', 'Stora Coop Danderyd', '', 'Danderyd', 'Coop'),
('coop-3460', 'coop', '3460', 'Stora Coop Jönköping', '', 'Jönköping', 'Coop'),
('coop-1850', 'coop', '1850', 'Stora Coop Gällivare', '', 'Gällivare', 'Coop'),
('coop-675', 'coop', '675', 'Stora Coop Nyköping', '', 'Nyköping', 'Coop'),
('coop-3478', 'coop', '3478', 'Stora Coop Norrteljeporten', '', 'Norrtälje', 'Coop'),
('coop-18', 'coop', '18', 'Stora Coop Stuvsta', '', 'Huddinge', 'Coop'),
('coop-89', 'coop', '89', 'Stora Coop Orminge', '', 'Saltsjö-Boo', 'Coop'),
('coop-1927', 'coop', '1927', 'Stora Coop Värmdö', '', 'Gustavsberg', 'Coop'),
('coop-640', 'coop', '640', 'Stora Coop Södertälje', '', 'Södertälje', 'Coop'),
('coop-3854', 'coop', '3854', 'Stora Coop Råå Hbg', '', 'Helsingborg', 'Coop'),
('coop-3852', 'coop', '3852', 'Stora Coop Väla Hbg', '', 'Ödåkra', 'Coop'),
('coop-2666', 'coop', '2666', 'Stora Coop Strängnäs', '', 'Strängnäs', 'Coop'),
('coop-659', 'coop', '659', 'Stora Coop Eskilstuna', '', 'Eskilstuna', 'Coop'),
('coop-652', 'coop', '652', 'Stora Coop Borås', '', 'Borås', 'Coop'),
('coop-1876', 'coop', '1876', 'Stora Coop Bollnäs', '', 'Bollnäs', 'Coop'),
('coop-1227', 'coop', '1227', 'Stora Coop Palmviken Arvika', '', 'Arvika', 'Coop'),
('coop-1253', 'coop', '1253', 'Stora Coop Styckåsen', '', 'Arvika', 'Coop'),
('coop-1975', 'coop', '1975', 'Stora Coop Hammarö', '', 'Hammarö', 'Coop'),
('coop-2814', 'coop', '2814', 'Stora Coop Åkersberga', '', 'Åkersberga', 'Coop'),
('coop-677', 'coop', '677', 'Stora Coop Enköping', '', 'Enköping', 'Coop')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, address = EXCLUDED.address, city = EXCLUDED.city, profile = EXCLUDED.profile;

-- Batch 2
INSERT INTO stores (id, chain_id, external_id, name, address, city, profile) VALUES
('coop-1926', 'coop', '1926', 'Stora Coop Örnäset', '', 'Luleå', 'Coop'),
('coop-1024', 'coop', '1024', 'Stora Coop Finspång', '', 'Finspång', 'Coop'),
('coop-3778', 'coop', '3778', 'Stora Coop Stenby Västerås', '', 'Västerås', 'Coop'),
('coop-639', 'coop', '639', 'Stora Coop Rotebro', '', 'Sollentuna', 'Coop'),
('coop-2239', 'coop', '2239', 'Stora Coop Sundsvall', '', 'Sundsvall', 'Coop'),
('coop-3805', 'coop', '3805', 'Stora Coop Halmstad', '', 'Halmstad', 'Coop'),
('coop-3150', 'coop', '3150', 'Stora Coop Norra Backa', '', 'Borlänge', 'Coop'),
('coop-3494', 'coop', '3494', 'Stora Coop Välsviken', '', 'Karlstad', 'Coop'),
('coop-2235', 'coop', '2235', 'Stora Coop Ludvika', '', 'Ludvika', 'Coop'),
('coop-3498', 'coop', '3498', 'Stora Coop Kungsängen', '', 'Kungsängen', 'Coop'),
('coop-2303', 'coop', '2303', 'Stora Coop Garnisonen Linköping', '', 'Linköping', 'Coop'),
('coop-3506', 'coop', '3506', 'Stora Coop Falun', '', 'Falun', 'Coop'),
('coop-3516', 'coop', '3516', 'Stora Coop Tomtebo', '', 'Umeå', 'Coop'),
('coop-3522', 'coop', '3522', 'Stora Coop Flygstaden', '', 'Eslöv', 'Coop'),
('coop-3532', 'coop', '3532', 'Stora Coop Tumba', '', 'Tumba', 'Coop'),
('coop-3851', 'coop', '3851', 'Stora Coop Trelleborg', '', 'Trelleborg', 'Coop'),
('coop-3594', 'coop', '3594', 'Stora Coop Torp', '', 'Uddevalla', 'Coop'),
('coop-3618', 'coop', '3618', 'Stora Coop Storlien', '', 'Storlien', 'Coop'),
('coop-3719', 'coop', '3719', 'Stora Coop Arninge', '', 'Täby', 'Coop'),
('coop-3759', 'coop', '3759', 'Stora Coop Härlöv', '', 'Kristianstad', 'Coop'),
('coop-3767', 'coop', '3767', 'Stora Coop Ljusdal', '', 'Ljusdal', 'Coop'),
('coop-3857', 'coop', '3857', 'Stora Coop Burlöv', '', 'Arlöv', 'Coop'),
('coop-1166', 'coop', '1166', 'Coop Konsum Frillesås', '', 'Frillesås', 'Coop'),
('coop-1129', 'coop', '1129', 'Coop Österport', '', 'Karlshamn', 'Coop'),
('coop-25', 'coop', '25', 'Coop Västerhaninge Centrum', '', 'Västerhaninge', 'Coop'),
('coop-212', 'coop', '212', 'Coop Västertorg', '', 'Uppsala', 'Coop'),
('coop-1230', 'coop', '1230', 'Coop Säffle', '', 'Säffle', 'Coop'),
('coop-1229', 'coop', '1229', 'Coop Filipstad', '', 'Filipstad', 'Coop'),
('coop-3849', 'coop', '3849', 'Coop Tomelilla', '', 'Tomelilla', 'Coop'),
('coop-3766', 'coop', '3766', 'Coop Hofors', '', 'Hofors', 'Coop'),
('coop-3850', 'coop', '3850', 'Coop Forum Jägersro', '', 'Malmö', 'Coop'),
('coop-1289', 'coop', '1289', 'Stora Coop Karlskoga', '', 'Karlskoga', 'Coop'),
('coop-636', 'coop', '636', 'Stora Coop Haninge', '', 'Haninge', 'Coop'),
('coop-2477', 'coop', '2477', 'Stora Coop Hus&Trädgård Skellefteå', '', 'Skellefteå', 'Coop'),
('coop-3848', 'coop', '3848', 'Coop Köpenhamnsvägen', '', 'Malmö', 'Coop'),
('coop-1363', 'coop', '1363', 'Coop Älvkarleby', '', 'Älvkarleby 1', 'Coop'),
('coop-1260', 'coop', '1260', 'Coop Årjäng', '', 'Årjäng', 'Coop'),
('coop-1373', 'coop', '1373', 'Coop Bergvik', '', 'Bergvik', 'Coop'),
('coop-1571', 'coop', '1571', 'Coop Haparanda', '', 'Haparanda', 'Coop'),
('coop-1232', 'coop', '1232', 'Coop Sunne', '', 'Sunne', 'Coop'),
('coop-1228', 'coop', '1228', 'Coop Hagfors', '', 'Hagfors', 'Coop'),
('coop-1187', 'coop', '1187', 'Coop Bengtsfors', '', 'Bengtsfors', 'Coop'),
('coop-1194', 'coop', '1194', 'Coop Hunnebostrand', '', 'Hunnebostrand', 'Coop'),
('coop-1198', 'coop', '1198', 'Coop Grebbestad', '', 'Grebbestad', 'Coop'),
('coop-1212', 'coop', '1212', 'Coop Sjuntorp', '', 'Sjuntorp', 'Coop'),
('coop-1216', 'coop', '1216', 'Coop Ed', '', 'Ed', 'Coop'),
('coop-1331', 'coop', '1331', 'Coop Grycksbo', '', 'Grycksbo', 'Coop'),
('coop-1329', 'coop', '1329', 'Coop Bjursås', '', 'Bjursås', 'Coop'),
('coop-1365', 'coop', '1365', 'Coop Enen', '', 'Sandviken', 'Coop'),
('coop-1368', 'coop', '1368', 'Coop Storvik', '', 'Storvik', 'Coop'),
('coop-1351', 'coop', '1351', 'Coop Forsbacka', '', 'Forsbacka', 'Coop'),
('coop-1345', 'coop', '1345', 'Coop Ljusne', '', 'Ljusne', 'Coop'),
('coop-1374', 'coop', '1374', 'Coop Kilafors', '', 'Kilafors', 'Coop'),
('coop-1562', 'coop', '1562', 'Coop Arjeplog', '', 'Arjeplog', 'Coop'),
('coop-1569', 'coop', '1569', 'Coop Råneå', '', 'Råneå', 'Coop'),
('coop-1559', 'coop', '1559', 'Coop Pajala', '', 'Pajala', 'Coop'),
('coop-917', 'coop', '917', 'Coop Skutskär', '', 'Skutskär', 'Coop'),
('coop-1192', 'coop', '1192', 'Coop Färgelanda', '', 'Färgelanda', 'Coop'),
('coop-187', 'coop', '187', 'Coop Klintehamn', '', 'Klintehamn', 'Coop'),
('coop-188', 'coop', '188', 'Coop Roma', '', 'Romakloster', 'Coop'),
('coop-189', 'coop', '189', 'Coop Ljugarn', '', 'Ljugarn', 'Coop'),
('coop-190', 'coop', '190', 'Coop Hemse', '', 'Hemse', 'Coop'),
('coop-191', 'coop', '191', 'Coop Lärbro', '', 'Lärbro', 'Coop'),
('coop-194', 'coop', '194', 'Coop Slite', '', 'Slite', 'Coop'),
('coop-1140', 'coop', '1140', 'Coop Eslöv', '', 'Eslöv', 'Coop'),
('coop-1099', 'coop', '1099', 'Coop Mörrum', '', 'Mörrum', 'Coop'),
('coop-1110', 'coop', '1110', 'Coop Degeberga', '', 'Degeberga', 'Coop'),
('coop-1113', 'coop', '1113', 'Coop Rödeby', '', 'Rödeby', 'Coop'),
('coop-1120', 'coop', '1120', 'Coop Kallinge', '', 'Kallinge', 'Coop'),
('coop-1128', 'coop', '1128', 'Coop Asarum', '', 'Asarum', 'Coop'),
('coop-164', 'coop', '164', 'Coop Gråbo', '', 'Visby', 'Coop'),
('coop-964', 'coop', '964', 'Coop Kungsberga', '', 'Färentuna', 'Coop'),
('coop-1036', 'coop', '1036', 'Coop Bergslagshallen', '', 'Finspång', 'Coop'),
('coop-1188', 'coop', '1188', 'Coop Åmål Mellanbrogatan', '', 'Åmål', 'Coop'),
('coop-1189', 'coop', '1189', 'Coop Kungshamn', '', 'Kungshamn', 'Coop'),
('coop-1196', 'coop', '1196', 'Coop Brastad', '', 'Brastad', 'Coop'),
('coop-1203', 'coop', '1203', 'Coop Munkedal', '', 'Munkedal', 'Coop'),
('coop-1211', 'coop', '1211', 'Coop Strömslund', '', 'Trollhättan', 'Coop'),
('coop-1338', 'coop', '1338', 'Coop Nian', '', 'Gävle', 'Coop'),
('coop-1349', 'coop', '1349', 'Coop Sandviken', '', 'Sandviken', 'Coop'),
('coop-1354', 'coop', '1354', 'Coop Krysset', '', 'Gävle', 'Coop'),
('coop-1565', 'coop', '1565', 'Coop Björkskatan', '', 'Luleå', 'Coop'),
('coop-1597', 'coop', '1597', 'Coop Sveafältet', '', 'Boden', 'Coop'),
('coop-1361', 'coop', '1361', 'Coop Triangeln Gävle', '', 'Gävle', 'Coop'),
('coop-334', 'coop', '334', 'Coop Österbymo', '', 'Ydre', 'Coop'),
('coop-1362', 'coop', '1362', 'Coop Karlholm', '', 'Karlholmsbruk', 'Coop'),
('coop-1360', 'coop', '1360', 'Coop Hallen', '', 'Gävle', 'Coop'),
('coop-1221', 'coop', '1221', 'Coop Åsensbruk', '', 'Åsensbruk', 'Coop'),
('coop-1048', 'coop', '1048', 'Coop Torup', '', 'Torup', 'Coop'),
('coop-1049', 'coop', '1049', 'Coop Unnaryd', '', 'Unnaryd', 'Coop'),
('coop-268', 'coop', '268', 'Coop Älmhult', '', 'Älmhult', 'Coop'),
('coop-274', 'coop', '274', 'Coop Gnosjö', '', 'Gnosjö', 'Coop'),
('coop-1053', 'coop', '1053', 'Coop Kosta', '', 'Kosta', 'Coop'),
('coop-1067', 'coop', '1067', 'Coop Överum', '', 'Överum', 'Coop'),
('coop-278', 'coop', '278', 'Coop Åseda', '', 'Åseda', 'Coop'),
('coop-280', 'coop', '280', 'Coop Bankeryd', '', 'Bankeryd', 'Coop'),
('coop-281', 'coop', '281', 'Coop Sävsjö', '', 'Sävsjö', 'Coop'),
('coop-283', 'coop', '283', 'Coop Habo', '', 'Habo', 'Coop'),
('coop-285', 'coop', '285', 'Coop Gränna', '', 'Gränna', 'Coop'),
('coop-287', 'coop', '287', 'Coop Aneby', '', 'Aneby', 'Coop')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, address = EXCLUDED.address, city = EXCLUDED.city, profile = EXCLUDED.profile;

-- Batch 3
INSERT INTO stores (id, chain_id, external_id, name, address, city, profile) VALUES
('coop-288', 'coop', '288', 'Coop Lessebo', '', 'Lessebo', 'Coop'),
('coop-1805', 'coop', '1805', 'Coop Nässjö', '', 'Nässjö', 'Coop'),
('coop-1889', 'coop', '1889', 'Coop Oxtorget', '', 'Växjö', 'Coop'),
('coop-310', 'coop', '310', 'Coop Torsås', '', 'Torsås', 'Coop'),
('coop-314', 'coop', '314', 'Coop Norrliden', '', 'Kalmar', 'Coop'),
('coop-325', 'coop', '325', 'Coop Mullsjö', '', 'Mullsjö', 'Coop'),
('coop-327', 'coop', '327', 'Coop Dalviksringen', '', 'Jönköping', 'Coop'),
('coop-338', 'coop', '338', 'Coop Ekenässjön', '', 'Ekenässjön', 'Coop'),
('coop-1075', 'coop', '1075', 'Coop Högö', '', 'Västervik', 'Coop'),
('coop-1081', 'coop', '1081', 'Coop Påskallavik', '', 'Påskallavik', 'Coop'),
('coop-1083', 'coop', '1083', 'Coop Figeholm', '', 'Figeholm', 'Coop'),
('coop-1085', 'coop', '1085', 'Coop Kristdala', '', 'Kristdala', 'Coop'),
('coop-1087', 'coop', '1087', 'Coop Högsby', '', 'Högsby', 'Coop'),
('coop-1158', 'coop', '1158', 'Coop Veberöd', '', 'Veberöd', 'Coop'),
('coop-1163', 'coop', '1163', 'Coop Getinge', '', 'Getinge', 'Coop'),
('coop-1207', 'coop', '1207', 'Coop Styrsö', '', 'Styrsö', 'Coop'),
('coop-1223', 'coop', '1223', 'Coop Hajom', '', 'Hajom', 'Coop'),
('coop-1240', 'coop', '1240', 'Stora Coop Kil', '', 'Kil', 'Coop'),
('coop-1233', 'coop', '1233', 'Coop Forshaga', '', 'Forshaga', 'Coop'),
('coop-1239', 'coop', '1239', 'Coop Lesjöfors', '', 'Lesjöfors', 'Coop'),
('coop-1243', 'coop', '1243', 'Coop Norrstrand', '', 'Karlstad', 'Coop'),
('coop-1254', 'coop', '1254', 'Coop Herrhagen', '', 'Karlstad', 'Coop'),
('coop-1255', 'coop', '1255', 'Coop Kronoparken', '', 'Karlstad', 'Coop'),
('coop-1263', 'coop', '1263', 'Coop Sysslebäck', '', 'Sysslebäck', 'Coop'),
('coop-1300', 'coop', '1300', 'Coop Fröding', '', 'Karlskoga', 'Coop'),
('coop-1303', 'coop', '1303', 'Coop Storängen', '', 'Karlskoga', 'Coop'),
('coop-1333', 'coop', '1333', 'Coop Sollerön', '', 'Sollerön', 'Coop'),
('coop-1441', 'coop', '1441', 'Coop Byske', '', 'Byske', 'Coop'),
('coop-1443', 'coop', '1443', 'Coop Norsjö', '', 'Norsjö', 'Coop'),
('coop-1445', 'coop', '1445', 'Coop Malå', '', 'Malå', 'Coop'),
('coop-1448', 'coop', '1448', 'Coop Tärnaby', '', 'Tärnaby', 'Coop'),
('coop-922', 'coop', '922', 'Coop Burträsk', '', 'Burträsk', 'Coop'),
('coop-1449', 'coop', '1449', 'Coop Ålidhem', '', 'Umeå', 'Coop'),
('coop-1450', 'coop', '1450', 'Coop Nordmaling', '', 'Nordmaling', 'Coop'),
('coop-1451', 'coop', '1451', 'Coop Storuman', '', 'Storuman', 'Coop'),
('coop-1454', 'coop', '1454', 'Coop Robertsfors', '', 'Robertsfors', 'Coop'),
('coop-1922', 'coop', '1922', 'Coop Hörnett', '', 'Domsjö', 'Coop'),
('coop-1404', 'coop', '1404', 'Coop Hammarstrand', '', 'Hammarstrand', 'Coop'),
('coop-1407', 'coop', '1407', 'Coop Åre', '', 'Åre', 'Coop'),
('coop-1408', 'coop', '1408', 'Coop Järpen', '', 'Järpen', 'Coop'),
('coop-1476', 'coop', '1476', 'Coop Bjurholm', '', 'Bjurholm', 'Coop'),
('coop-1494', 'coop', '1494', 'Coop Ursviken', '', 'Ursviken', 'Coop'),
('coop-1495', 'coop', '1495', 'Coop Erikslid', '', 'Skellefteå', 'Coop'),
('coop-618', 'coop', '618', 'Coop Själevad', '', 'Själevad', 'Coop'),
('coop-1164', 'coop', '1164', 'Coop Knäred', '', 'Knäred', 'Coop'),
('coop-921', 'coop', '921', 'Coop Kramfors', '', 'Kramfors', 'Coop'),
('coop-1388', 'coop', '1388', 'Coop Timrå', '', 'Timrå', 'Coop'),
('coop-1402', 'coop', '1402', 'Coop Strömsund', '', 'Strömsund', 'Coop'),
('coop-1412', 'coop', '1412', 'Coop Frösön', '', 'Frösön', 'Coop'),
('coop-924', 'coop', '924', 'Coop Vännäs', '', 'Vännäs', 'Coop'),
('coop-918', 'coop', '918', 'Coop Ånge', '', 'Ånge', 'Coop'),
('coop-1890', 'coop', '1890', 'Coop Nacksta', '', 'Sundsvall', 'Coop'),
('coop-1098', 'coop', '1098', 'Coop Lönsboda', '', 'Lönsboda', 'Coop'),
('coop-316', 'coop', '316', 'Coop Färjestaden', '', 'Färjestaden', 'Coop'),
('coop-1131', 'coop', '1131', 'Coop Svängsta', '', 'Svängsta', 'Coop'),
('coop-1419', 'coop', '1419', 'Coop Brunflo', '', 'Brunflo', 'Coop'),
('coop-2750', 'coop', '2750', 'Coop Lysekil', '', 'Lysekil', 'Coop'),
('coop-1237', 'coop', '1237', 'Coop Åmotfors', '', 'Åmotfors', 'Coop'),
('coop-272', 'coop', '272', 'Coop Tranås', '', 'Tranås', 'Coop'),
('coop-1213', 'coop', '1213', 'Coop Hörngatan', '', 'Trollhättan', 'Coop'),
('coop-1195', 'coop', '1195', 'Coop Karlstadsvägen', '', 'Åmål', 'Coop'),
('coop-1558', 'coop', '1558', 'Coop Älvsbyn', '', 'Älvsbyn', 'Coop'),
('coop-2815', 'coop', '2815', 'Coop Värnamo', '', 'Värnamo', 'Coop'),
('coop-1080', 'coop', '1080', 'Coop Kolberga', '', 'Oskarshamn', 'Coop'),
('coop-1111', 'coop', '1111', 'Coop Broby', '', 'Broby', 'Coop'),
('coop-2816', 'coop', '2816', 'Coop Östra Torget', '', 'Jönköping', 'Coop'),
('coop-1442', 'coop', '1442', 'Coop Bureå', '', 'Bureå', 'Coop'),
('coop-1242', 'coop', '1242', 'Stora Coop Torsby', '', 'Torsby', 'Coop'),
('coop-1185', 'coop', '1185', 'Coop Rosviksgatan', '', 'Lysekil', 'Coop'),
('coop-1346', 'coop', '1346', 'Coop Norrsundet', '', 'Norrsundet', 'Coop'),
('coop-1095', 'coop', '1095', 'Coop Hässleholm', '', 'Hässleholm', 'Coop'),
('coop-1104', 'coop', '1104', 'Coop Sölvesborg', '', 'Sölvesborg', 'Coop'),
('coop-1118', 'coop', '1118', 'Coop Knislinge', '', 'Knislinge', 'Coop'),
('coop-1215', 'coop', '1215', 'Coop Mustadfors', '', 'Dals-Långed', 'Coop'),
('coop-1190', 'coop', '1190', 'Coop Skogslyckan', '', 'Uddevalla', 'Coop'),
('coop-1209', 'coop', '1209', 'Coop Bäckefors', '', 'Bäckefors', 'Coop'),
('coop-1193', 'coop', '1193', 'Coop Högsäter', '', 'Högsäter', 'Coop'),
('coop-1210', 'coop', '1210', 'Coop Fjällbacka', '', 'Fjällbacka', 'Coop'),
('coop-1066', 'coop', '1066', 'Coop Flanaden', '', 'Oskarshamn', 'Coop'),
('coop-229', 'coop', '229', 'Coop Boxholm', '', 'Boxholm', 'Coop'),
('coop-231', 'coop', '231', 'Coop Kisa', '', 'Kisa', 'Coop'),
('coop-2229', 'coop', '2229', 'Coop Stenbärsvägen Nyköping', '', 'Nyköping', 'Coop'),
('coop-21', 'coop', '21', 'Coop Gnesta', '', 'Gnesta', 'Coop'),
('coop-22', 'coop', '22', 'Coop Tungelsta', '', 'Tungelsta', 'Coop'),
('coop-247', 'coop', '247', 'Coop Skarphagen', '', 'Norrköping', 'Coop'),
('coop-44', 'coop', '44', 'Coop Björkhagen', '', 'Johanneshov', 'Coop'),
('coop-47', 'coop', '47', 'Coop Vintertullen', '', 'Stockholm', 'Coop'),
('coop-3823', 'coop', '3823', 'Coop Värnhem', '', 'Malmö', 'Coop'),
('coop-51', 'coop', '51', 'Coop Farsta Strand', '', 'Farsta', 'Coop'),
('coop-3825', 'coop', '3825', 'Coop Högalid', '', 'Trelleborg', 'Coop'),
('coop-530', 'coop', '530', 'Coop Hälleforsnäs', '', 'Hälleforsnäs', 'Coop'),
('coop-126', 'coop', '126', 'Coop Östgötagatan', '', 'Stockholm', 'Coop'),
('coop-130', 'coop', '130', 'Coop Vendelsömalm', '', 'Haninge', 'Coop'),
('coop-143', 'coop', '143', 'Coop Hölö', '', 'Hölö', 'Coop'),
('coop-180', 'coop', '180', 'Coop Tibble', '', 'Kungsängen', 'Coop'),
('coop-211', 'coop', '211', 'Coop Ringgatan', '', 'Uppsala', 'Coop'),
('coop-214', 'coop', '214', 'Coop Storvreta', '', 'Storvreta', 'Coop'),
('coop-83', 'coop', '83', 'Coop Sockenplan', '', 'Enskede', 'Coop'),
('coop-271', 'coop', '271', 'Coop Eksjö', '', 'Eksjö', 'Coop'),
('coop-335', 'coop', '335', 'Coop Tenhult', '', 'Tenhult', 'Coop')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, address = EXCLUDED.address, city = EXCLUDED.city, profile = EXCLUDED.profile;

-- Batch 4
INSERT INTO stores (id, chain_id, external_id, name, address, city, profile) VALUES
('coop-1853', 'coop', '1853', 'Coop Kristinedal', '', 'Jönköping', 'Coop'),
('coop-3137', 'coop', '3137', 'Coop Älvängen', '', 'Älvängen', 'Coop'),
('coop-121', 'coop', '121', 'Coop Spånga Torg', '', 'Spånga', 'Coop'),
('coop-1274', 'coop', '1274', 'Coop Skived', '', 'Forshaga', 'Coop'),
('coop-1439', 'coop', '1439', 'Coop Sollefteå', '', 'Sollefteå', 'Coop'),
('coop-88', 'coop', '88', 'Coop Södertälje C', '', 'Södertälje', 'Coop'),
('coop-1246', 'coop', '1246', 'Coop Molkom', '', 'Molkom', 'Coop'),
('coop-1238', 'coop', '1238', 'Coop Charlottenberg', '', 'Charlottenberg', 'Coop'),
('coop-1257', 'coop', '1257', 'Coop Koppom', '', 'Koppom', 'Coop'),
('coop-596', 'coop', '596', 'Coop Sälen', '', 'Sälen', 'Coop'),
('coop-578', 'coop', '578', 'Coop Forssa', '', 'Borlänge', 'Coop'),
('coop-574', 'coop', '574', 'Coop Rättvik', '', 'Rättvik', 'Coop'),
('coop-573', 'coop', '573', 'Coop Kvarnberget', '', 'Falun', 'Coop'),
('coop-572', 'coop', '572', 'Coop Ludvika Gård', '', 'Ludvika', 'Coop'),
('coop-570', 'coop', '570', 'Coop Vansbro', '', 'Vansbro', 'Coop'),
('coop-569', 'coop', '569', 'Coop Grängesberg', '', 'Grängesberg', 'Coop'),
('coop-568', 'coop', '568', 'Coop Smedjebacken', '', 'Smedjebacken', 'Coop'),
('coop-567', 'coop', '567', 'Coop Orsa', '', 'Orsa', 'Coop'),
('coop-566', 'coop', '566', 'Coop Säter', '', 'Säter', 'Coop'),
('coop-559', 'coop', '559', 'Coop Östervåla', '', 'Östervåla', 'Coop'),
('coop-529', 'coop', '529', 'Coop Heby', '', 'Heby', 'Coop'),
('coop-528', 'coop', '528', 'Coop Skinnskatteberg', '', 'Skinnskatteberg', 'Coop'),
('coop-527', 'coop', '527', 'Coop Norberg', '', 'Norberg', 'Coop'),
('coop-520', 'coop', '520', 'Coop Fagersta', '', 'Fagersta', 'Coop'),
('coop-203', 'coop', '203', 'Coop Östhammar', '', 'Östhammar', 'Coop'),
('coop-202', 'coop', '202', 'Coop Hallstavik', '', 'Hallstavik', 'Coop'),
('coop-199', 'coop', '199', 'Coop Tierp', '', 'Tierp', 'Coop'),
('coop-198', 'coop', '198', 'Coop Österbybruk', '', 'Österbybruk', 'Coop'),
('coop-1997', 'coop', '1997', 'Stora Coop Östhammar', '', 'Östhammar', 'Coop'),
('coop-2809', 'coop', '2809', 'Coop Änghagen Lidköping', '', 'Lidköping', 'Coop'),
('coop-2702', 'coop', '2702', 'Coop Vipans Gränd Skövde', '', 'Skövde', 'Coop'),
('coop-473', 'coop', '473', 'Coop Karlsborg', '', 'Karlsborg', 'Coop'),
('coop-472', 'coop', '472', 'Coop Kyrkogatan Töreboda', '', 'Töreboda', 'Coop'),
('coop-474', 'coop', '474', 'Coop Sydport Mariestad', '', 'Mariestad', 'Coop'),
('coop-471', 'coop', '471', 'Coop Tidaholm', '', 'Tidaholm', 'Coop'),
('coop-2236', 'coop', '2236', 'Coop Falköping', '', 'Falköping', 'Coop'),
('coop-466', 'coop', '466', 'Coop Skene', '', 'Skene', 'Coop'),
('coop-454', 'coop', '454', 'Coop Surte', '', 'Surte', 'Coop'),
('coop-449', 'coop', '449', 'Coop Gamlestaden', '', 'Göteborg', 'Coop'),
('coop-1888', 'coop', '1888', 'Coop Eriksberg', '', 'Göteborg', 'Coop'),
('coop-438', 'coop', '438', 'Coop Munkebäckstorg', '', 'Göteborg', 'Coop'),
('coop-2704', 'coop', '2704', 'Coop Friggagatan', '', 'Göteborg', 'Coop'),
('coop-434', 'coop', '434', 'Coop Landala', '', 'Göteborg', 'Coop'),
('coop-430', 'coop', '430', 'Coop Avenyn', '', 'Göteborg', 'Coop'),
('coop-423', 'coop', '423', 'Coop Stenungsund', '', 'Stenungsund', 'Coop'),
('coop-421', 'coop', '421', 'Coop Lundby', '', 'Göteborg', 'Coop'),
('coop-3793', 'coop', '3793', 'Coop Garphyttan', '', 'Garphyttan', 'Coop'),
('coop-1090', 'coop', '1090', 'Coop Virserum', '', 'Virserum', 'Coop'),
('coop-1321', 'coop', '1321', 'Coop Älvdalen', '', 'Älvdalen', 'Coop'),
('coop-1322', 'coop', '1322', 'Coop Särna', '', 'Särna', 'Coop'),
('coop-1326', 'coop', '1326', 'Coop Idre', '', 'Idre', 'Coop'),
('coop-30', 'coop', '30', 'Coop Tyresö Centrum', '', 'Tyresö', 'Coop'),
('coop-2273', 'coop', '2273', 'Coop Björnboda', '', 'Vällingby', 'Coop'),
('coop-3772', 'coop', '3772', 'Coop Pilgatan Västerås', '', 'Västerås', 'Coop'),
('coop-3818', 'coop', '3818', 'Coop Simrishamn', '', 'Simrishamn', 'Coop'),
('coop-3824', 'coop', '3824', 'Coop Smygehamn', '', 'Smygehamn', 'Coop'),
('coop-653', 'coop', '653', 'Coop Kållered', '', 'Kållered', 'Coop'),
('coop-1107', 'coop', '1107', 'Coop Hasslö', '', 'Hasslö', 'Coop'),
('coop-3792', 'coop', '3792', 'Coop Änggatan', '', 'Örebro', 'Coop'),
('coop-252', 'coop', '252', 'Coop Värmlandsgatan', '', 'Norrköping', 'Coop'),
('coop-253', 'coop', '253', 'Coop Trozelligatan', '', 'Norrköping', 'Coop'),
('coop-1281', 'coop', '1281', 'Coop Lysvik', '', 'Lysvik', 'Coop'),
('coop-442', 'coop', '442', 'Coop Trätorget', '', 'Göteborg', 'Coop'),
('coop-2207', 'coop', '2207', 'Coop Daglivs', '', 'Stockholm', 'Coop'),
('coop-3496', 'coop', '3496', 'Coop Ingmarsö', '', 'Möja', 'Coop'),
('coop-3497', 'coop', '3497', 'Coop Kronhjorten', '', 'Trollhättan', 'Coop'),
('coop-104', 'coop', '104', 'Coop Järntorget', '', 'Stockholm', 'Coop'),
('coop-1269', 'coop', '1269', 'Coop Svanskog', '', 'Svanskog', 'Coop'),
('coop-1369', 'coop', '1369', 'Coop Kungsgården', '', 'Kungsgården', 'Coop'),
('coop-1383', 'coop', '1383', 'Coop Hassela', '', 'Hassela', 'Coop'),
('coop-1604', 'coop', '1604', 'Coop Sangis', '', 'Sangis', 'Coop'),
('coop-1041', 'coop', '1041', 'Coop Rejmyre', '', 'Rejmyre', 'Coop'),
('coop-293', 'coop', '293', 'Coop Kristinatorget', '', 'Växjö', 'Coop'),
('coop-305', 'coop', '305', 'Coop Traryd', '', 'Traryd', 'Coop'),
('coop-1279', 'coop', '1279', 'Coop Vikene', '', 'Brunskog', 'Coop'),
('coop-1280', 'coop', '1280', 'Coop Högboda', '', 'Kil', 'Coop'),
('coop-1286', 'coop', '1286', 'Coop Skillingsfors', '', 'Skillingsfors', 'Coop'),
('coop-1364', 'coop', '1364', 'Coop Hagaström', '', 'Gävle', 'Coop'),
('coop-1560', 'coop', '1560', 'Coop Harads', '', 'Harads', 'Coop'),
('coop-966', 'coop', '966', 'Coop Berg', '', 'Möja', 'Coop'),
('coop-967', 'coop', '967', 'Coop Långvik', '', 'Långvik', 'Coop'),
('coop-333', 'coop', '333', 'Coop Visingsö', '', 'Visingsö', 'Coop'),
('coop-339', 'coop', '339', 'Coop Bor', '', 'Bor', 'Coop'),
('coop-1076', 'coop', '1076', 'Coop Edsbruk', '', 'Edsbruk', 'Coop'),
('coop-1078', 'coop', '1078', 'Coop Fårbo', '', 'Fårbo', 'Coop'),
('coop-1082', 'coop', '1082', 'Coop Berga', '', 'Berga', 'Coop'),
('coop-1089', 'coop', '1089', 'Coop Alsterbro', '', 'Alsterbro', 'Coop'),
('coop-1285', 'coop', '1285', 'Coop Sunnemo', '', 'Sunnemo', 'Coop'),
('coop-1287', 'coop', '1287', 'Coop Stöllet', '', 'Stöllet', 'Coop'),
('coop-1444', 'coop', '1444', 'Coop Sorsele', '', 'Sorsele', 'Coop'),
('coop-1447', 'coop', '1447', 'Coop Dorotea', '', 'Dorotea', 'Coop'),
('coop-923', 'coop', '923', 'Coop Åsele', '', 'Åsele', 'Coop'),
('coop-1453', 'coop', '1453', 'Coop Hörnefors', '', 'Hörnefors', 'Coop'),
('coop-1457', 'coop', '1457', 'Coop Bollstabruk', '', 'Bollstabruk', 'Coop'),
('coop-1462', 'coop', '1462', 'Coop Ersboda', '', 'Umeå', 'Coop'),
('coop-1464', 'coop', '1464', 'Coop Vännäsby', '', 'Vännäsby', 'Coop'),
('coop-1465', 'coop', '1465', 'Coop Haga Umeå', '', 'Umeå', 'Coop'),
('coop-1483', 'coop', '1483', 'Coop Jörn', '', 'Jörn', 'Coop'),
('coop-1485', 'coop', '1485', 'Coop Lövånger', '', 'Lövånger', 'Coop'),
('coop-613', 'coop', '613', 'Coop Köpmanholmen', '', 'Köpmanholmen', 'Coop')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, address = EXCLUDED.address, city = EXCLUDED.city, profile = EXCLUDED.profile;

-- Batch 5
INSERT INTO stores (id, chain_id, external_id, name, address, city, profile) VALUES
('coop-615', 'coop', '615', 'Coop Mellansel', '', 'Mellansel', 'Coop'),
('coop-616', 'coop', '616', 'Coop Bredbyn', '', 'Bredbyn', 'Coop'),
('coop-927', 'coop', '927', 'Coop Torpshammar', '', 'Torpshammar', 'Coop'),
('coop-1526', 'coop', '1526', 'Coop Bergsåker', '', 'Sundsvall', 'Coop'),
('coop-1531', 'coop', '1531', 'Coop Fränsta', '', 'Fränsta', 'Coop'),
('coop-1537', 'coop', '1537', 'Coop Näsåker', '', 'Näsåker', 'Coop'),
('coop-1417', 'coop', '1417', 'Coop Torvalla', '', 'Östersund', 'Coop'),
('coop-1304', 'coop', '1304', 'Coop Bråten', '', 'Karlskoga', 'Coop'),
('coop-239', 'coop', '239', 'Coop Vallaplan', '', 'Linköping', 'Coop'),
('coop-248', 'coop', '248', 'Coop Hantverkaregatan', '', 'Norrköping', 'Coop'),
('coop-265', 'coop', '265', 'Coop Tystberga', '', 'Tystberga', 'Coop'),
('coop-46', 'coop', '46', 'Coop Mariatorget', '', 'Stockholm', 'Coop'),
('coop-3802', 'coop', '3802', 'Coop Furuvägen', '', 'Halmstad', 'Coop'),
('coop-50', 'coop', '50', 'Coop Tranebergsvägen', '', 'Bromma', 'Coop'),
('coop-53', 'coop', '53', 'Coop Västertorp', '', 'Hägersten', 'Coop'),
('coop-3832', 'coop', '3832', 'Coop Nobeltorget', '', 'Malmö', 'Coop'),
('coop-3833', 'coop', '3833', 'Coop Malmö Central', '', 'Malmö', 'Coop'),
('coop-3835', 'coop', '3835', 'Coop Kornettsgatan', '', 'Malmö', 'Coop'),
('coop-3837', 'coop', '3837', 'Coop Trollebergsvägen', '', 'Lund', 'Coop'),
('coop-3839', 'coop', '3839', 'Coop Flöjtvägen', '', 'Lund', 'Coop'),
('coop-3845', 'coop', '3845', 'Coop Örebrogatan', '', 'Helsingborg', 'Coop'),
('coop-73', 'coop', '73', 'Coop Tomtebogatan', '', 'Stockholm', 'Coop'),
('coop-532', 'coop', '532', 'Coop Högsjö', '', 'Högsjö', 'Coop'),
('coop-534', 'coop', '534', 'Coop Kyrkogatan', '', 'Katrineholm', 'Coop'),
('coop-540', 'coop', '540', 'Coop Skogstorp', '', 'Skogstorp', 'Coop'),
('coop-541', 'coop', '541', 'Coop Ärla', '', 'Ärla', 'Coop'),
('coop-3141', 'coop', '3141', 'Coop Älvsjö', '', 'Älvsjö', 'Coop'),
('coop-90', 'coop', '90', 'Coop Stamgatan', '', 'Älvsjö', 'Coop'),
('coop-97', 'coop', '97', 'Coop Vasalund', '', 'Solna', 'Coop'),
('coop-105', 'coop', '105', 'Coop Ribby', '', 'Västerhaninge', 'Coop'),
('coop-3079', 'coop', '3079', 'Coop Centralen', '', 'Stockholm', 'Coop'),
('coop-111', 'coop', '111', 'Coop Essingen', '', 'Stockholm', 'Coop'),
('coop-115', 'coop', '115', 'Coop Farmarstigen', '', 'Tyresö', 'Coop'),
('coop-127', 'coop', '127', 'Coop Sveavägen', '', 'Stockholm', 'Coop'),
('coop-129', 'coop', '129', 'Coop Svandammsplan', '', 'Hägersten', 'Coop'),
('coop-174', 'coop', '174', 'Coop Väsby Station', '', 'Upplands Väsby', 'Coop'),
('coop-178', 'coop', '178', 'Coop Barkarby', '', 'Järfälla', 'Coop'),
('coop-179', 'coop', '179', 'Coop Veckovägen', '', 'Järfälla', 'Coop'),
('coop-207', 'coop', '207', 'Coop Sunnersta', '', 'Uppsala', 'Coop'),
('coop-208', 'coop', '208', 'Coop Ekeby Uppsala', '', 'Uppsala', 'Coop'),
('coop-219', 'coop', '219', 'Coop Almunge', '', 'Almunge', 'Coop'),
('coop-220', 'coop', '220', 'Coop Grindvägen', '', 'Norrtälje', 'Coop'),
('coop-114', 'coop', '114', 'Coop Bromsten', '', 'Spånga', 'Coop'),
('coop-3148', 'coop', '3148', 'Coop City Kristianstad', '', 'Kristianstad', 'Coop'),
('coop-149', 'coop', '149', 'Coop Spångbro', '', 'Sorunda', 'Coop'),
('coop-1435', 'coop', '1435', 'Coop Lycksele', '', 'Lycksele', 'Coop'),
('coop-101', 'coop', '101', 'Coop Spångavägen', '', 'Spånga', 'Coop'),
('coop-43', 'coop', '43', 'Coop Fruängen', '', 'Hägersten', 'Coop'),
('coop-298', 'coop', '298', 'Coop Södra Ringvägen', '', 'Växjö', 'Coop'),
('coop-7', 'coop', '7', 'Coop Odenplan', '', 'Stockholm', 'Coop'),
('coop-133', 'coop', '133', 'Coop Reimersholme', '', 'Stockholm', 'Coop'),
('coop-38', 'coop', '38', 'Coop Kristineberg', '', 'Stockholm', 'Coop'),
('coop-134', 'coop', '134', 'Coop Mälarhöjden', '', 'Hägersten', 'Coop'),
('coop-3847', 'coop', '3847', 'Coop Lomma', '', 'Lomma', 'Coop'),
('coop-3414', 'coop', '3414', 'Coop Hötorget', '', 'Stockholm', 'Coop'),
('coop-3844', 'coop', '3844', 'Coop Knutpunkten', '', 'Helsingborg', 'Coop'),
('coop-3413', 'coop', '3413', 'Coop Renstiernas Gata', '', 'Stockholm', 'Coop'),
('coop-336', 'coop', '336', 'Coop Forserum', '', 'Forserum', 'Coop'),
('coop-1056', 'coop', '1056', 'Coop Lenhovda', '', 'Lenhovda', 'Coop'),
('coop-3803', 'coop', '3803', 'Coop Gamletull Halmstad', '', 'Halmstad', 'Coop'),
('coop-1355', 'coop', '1355', 'Coop Eken Gävle', '', 'Gävle', 'Coop'),
('coop-26', 'coop', '26', 'Coop Järna', '', 'Järna', 'Coop'),
('coop-1200', 'coop', '1200', 'Coop Malmön', '', 'Bohus-Malmön', 'Coop'),
('coop-608', 'coop', '608', 'Coop Enånger', '', 'Enånger', 'Coop'),
('coop-591', 'coop', '591', 'Coop Sunnansjö', '', 'Sunnansjö', 'Coop'),
('coop-581', 'coop', '581', 'Coop Djurås', '', 'Djurås', 'Coop'),
('coop-509', 'coop', '509', 'Coop Fredriksberg', '', 'Fredriksberg', 'Coop'),
('coop-480', 'coop', '480', 'Coop Hällekis', '', 'Hällekis', 'Coop'),
('coop-461', 'coop', '461', 'Coop Kyrkbytorget', '', 'Göteborg', 'Coop'),
('coop-453', 'coop', '453', 'Coop Gastorp', '', 'Lindome', 'Coop'),
('coop-3411', 'coop', '3411', 'Coop Alingsås', '', 'Alingsås', 'Coop'),
('coop-451', 'coop', '451', 'Coop Marstrand', '', 'Marstrand', 'Coop'),
('coop-448', 'coop', '448', 'Coop Mariagatan', '', 'Göteborg', 'Coop'),
('coop-444', 'coop', '444', 'Coop Käringberget', '', 'Västra Frölunda', 'Coop'),
('coop-435', 'coop', '435', 'Coop Dr Bex Gata', '', 'Göteborg', 'Coop'),
('coop-3777', 'coop', '3777', 'Coop Östanås', '', 'Köping', 'Coop'),
('coop-3774', 'coop', '3774', 'Coop Karlfeldtsplatsen', '', 'Västerås', 'Coop'),
('coop-3790', 'coop', '3790', 'Coop Rosta', '', 'Örebro', 'Coop'),
('coop-3787', 'coop', '3787', 'Stora Coop Ladugårdsängen', '', 'Örebro', 'Coop'),
('coop-3786', 'coop', '3786', 'Coop Österplan', '', 'Örebro', 'Coop'),
('coop-3440', 'coop', '3440', 'Coop Anderstorp', '', 'Anderstorp', 'Coop'),
('coop-3441', 'coop', '3441', 'Coop Atollen Jönköping', '', 'Jönköping', 'Coop'),
('coop-3442', 'coop', '3442', 'Coop Baronen Kalmar', '', 'Kalmar', 'Coop'),
('coop-125', 'coop', '125', 'Coop Bergshamra', '', 'Solna', 'Coop'),
('coop-137', 'coop', '137', 'Coop Nytorgsgatan', '', 'Stockholm', 'Coop'),
('coop-36', 'coop', '36', 'Coop Storsjövägen', '', 'Årsta', 'Coop'),
('coop-1171', 'coop', '1171', 'Coop Söder', '', 'Varberg', 'Coop'),
('coop-1172', 'coop', '1172', 'Coop Håsten', '', 'Varberg', 'Coop'),
('coop-1579', 'coop', '1579', 'Coop Vittangi', '', 'Vittangi', 'Coop'),
('coop-1580', 'coop', '1580', 'Coop Svappavaara', '', 'Svappavaara', 'Coop'),
('coop-1581', 'coop', '1581', 'Coop Jukkasjärvi', '', 'Jukkasjärvi', 'Coop'),
('coop-2798', 'coop', '2798', 'Coop Gällivare Luleåvägen', '', 'Gällivare', 'Coop'),
('coop-1616', 'coop', '1616', 'Coop Vuollerim', '', 'Vuollerim', 'Coop'),
('coop-3455', 'coop', '3455', 'Coop Gullänget', '', 'Örnsköldsvik', 'Coop'),
('coop-17', 'coop', '17', 'Coop Nynäshamn', '', 'Nynäshamn', 'Coop'),
('coop-86', 'coop', '86', 'Coop Zinken', '', 'Stockholm', 'Coop'),
('coop-1557', 'coop', '1557', 'Coop Övertorneå', '', 'Övertorneå', 'Coop'),
('coop-2450', 'coop', '2450', 'Coop Loet', '', 'Luleå', 'Coop'),
('coop-1592', 'coop', '1592', 'Coop Munksund', '', 'Piteå', 'Coop'),
('coop-1609', 'coop', '1609', 'Coop Mjölkudden', '', 'Luleå', 'Coop')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, address = EXCLUDED.address, city = EXCLUDED.city, profile = EXCLUDED.profile;

-- Batch 6
INSERT INTO stores (id, chain_id, external_id, name, address, city, profile) VALUES
('coop-1433', 'coop', '1433', 'Coop City Umeå', '', 'Umeå', 'Coop'),
('coop-3771', 'coop', '3771', 'Coop Laholm', '', 'Laholm', 'Coop'),
('coop-9', 'coop', '9', 'Coop Gröndal', '', 'Stockholm', 'Coop'),
('coop-13', 'coop', '13', 'Coop Högdalen', '', 'Bandhagen', 'Coop'),
('coop-56', 'coop', '56', 'Coop Bagarmossen', '', 'Bagarmossen', 'Coop'),
('coop-3816', 'coop', '3816', 'Coop Norra Parkgatan', '', 'Malmö', 'Coop'),
('coop-32', 'coop', '32', 'Coop Farsta', '', 'Farsta', 'Coop'),
('coop-1046', 'coop', '1046', 'Coop Norrahammar', '', 'Norrahammar', 'Coop'),
('coop-1047', 'coop', '1047', 'Coop Hovslätt', '', 'Jönköping', 'Coop'),
('coop-1050', 'coop', '1050', 'Coop Taberg', '', 'Taberg', 'Coop'),
('coop-1567', 'coop', '1567', 'Coop Bergnäset', '', 'Luleå', 'Coop'),
('coop-1573', 'coop', '1573', 'Coop Jokkmokk', '', 'Jokkmokk', 'Coop'),
('coop-3821', 'coop', '3821', 'Coop Örkelljunga', '', 'Örkelljunga', 'Coop'),
('coop-622', 'coop', '622', 'Coop Trehörningsjö', '', 'Trehörningsjö', 'Coop'),
('coop-3429', 'coop', '3429', 'Coop Tanumshede', '', 'Tanum', 'Coop'),
('coop-1474', 'coop', '1474', 'Coop Grisbacka', '', 'Umeå', 'Coop'),
('coop-1528', 'coop', '1528', 'Coop Haga Sundsvall', '', 'Sundsvall', 'Coop'),
('coop-2305', 'coop', '2305', 'Coop Medborgarplatsen', '', 'Stockholm', 'Coop'),
('coop-3463', 'coop', '3463', 'Coop Sundborn', '', 'Sundborn', 'Coop'),
('coop-1180', 'coop', '1180', 'Coop Strömstad', '', 'Strömstad', 'Coop'),
('coop-3088', 'coop', '3088', 'Coop Öster', '', 'Visby', 'Coop'),
('coop-634', 'coop', '634', 'Coop Funäsdalen', '', 'Funäsdalen', 'Coop'),
('coop-1452', 'coop', '1452', 'Coop Holmsund', '', 'Holmsund', 'Coop'),
('coop-913', 'coop', '913', 'Coop Mönsterås', '', 'Mönsterås', 'Coop'),
('coop-1070', 'coop', '1070', 'Coop Hultsfred', '', 'Hultsfred', 'Coop'),
('coop-1088', 'coop', '1088', 'Coop Blomstermåla', '', 'Blomstermåla', 'Coop'),
('coop-1091', 'coop', '1091', 'Coop Målilla', '', 'Målilla', 'Coop'),
('coop-3826', 'coop', '3826', 'Coop Höllviken', '', 'Höllviken', 'Coop'),
('coop-3820', 'coop', '3820', 'Coop Klostergården', '', 'Lund', 'Coop'),
('coop-3843', 'coop', '3843', 'Coop Kopparmöllegatan', '', 'Helsingborg', 'Coop'),
('coop-3846', 'coop', '3846', 'Coop Stenbocksgatan', '', 'Helsingborg', 'Coop'),
('coop-1141', 'coop', '1141', 'Coop Höör', '', 'Höör', 'Coop'),
('coop-255', 'coop', '255', 'Coop Krokek', '', 'Kolmården', 'Coop'),
('coop-3223', 'coop', '3223', 'Coop Smålandsstenar', '', 'Smålandsstenar', 'Coop'),
('coop-563', 'coop', '563', 'Coop Leksand', '', 'Leksand', 'Coop'),
('coop-1245', 'coop', '1245', 'Coop Storfors', '', 'Storfors', 'Coop'),
('coop-1264', 'coop', '1264', 'Coop Skattkärr', '', 'Skattkärr', 'Coop'),
('coop-1106', 'coop', '1106', 'Coop Nättraby', '', 'Nättraby', 'Coop'),
('coop-2200', 'coop', '2200', 'Coop Vällingby Centrum', '', 'Vällingby', 'Coop'),
('coop-537', 'coop', '537', 'Coop Triangeln Eskilstuna', '', 'Eskilstuna', 'Coop'),
('coop-3842', 'coop', '3842', 'Coop Ängelholm', '', 'Ängelholm', 'Coop'),
('coop-254', 'coop', '254', 'Stora Coop Risängen', '', 'Norrköping', 'Coop'),
('coop-429', 'coop', '429', 'Coop Mölnlycke', '', 'Mölnlycke', 'Coop'),
('coop-2800', 'coop', '2800', 'Coop Skeppet', '', 'Lidingö', 'Coop'),
('coop-2802', 'coop', '2802', 'Coop Torsvik', '', 'Lidingö', 'Coop'),
('coop-3813', 'coop', '3813', 'Coop Mårtenstorget', '', 'Lund', 'Coop'),
('coop-3831', 'coop', '3831', 'Coop Djupadal', '', 'Limhamn', 'Coop'),
('coop-240', 'coop', '240', 'Coop Lägerhyddan', '', 'Linköping', 'Coop'),
('coop-168', 'coop', '168', 'Coop Hemmesta', '', 'Värmdö', 'Coop'),
('coop-93', 'coop', '93', 'Coop Västra Skogen', '', 'Solna', 'Coop'),
('coop-1116', 'coop', '1116', 'Coop Vä', '', 'Kristianstad', 'Coop'),
('coop-186', 'coop', '186', 'Coop Kallhäll', '', 'Järfälla', 'Coop'),
('coop-633', 'coop', '633', 'Coop Sveg', '', 'Sveg', 'Coop'),
('coop-1455', 'coop', '1455', 'Coop Vindeln', '', 'Vindeln', 'Coop'),
('coop-920', 'coop', '920', 'Coop Vilhelmina', '', 'Vilhelmina', 'Coop'),
('coop-1401', 'coop', '1401', 'Coop Bräcke', '', 'Bräcke', 'Coop'),
('coop-1556', 'coop', '1556', 'Coop Överkalix', '', 'Överkalix', 'Coop'),
('coop-3822', 'coop', '3822', 'Coop Ystad', '', 'Ystad', 'Coop'),
('coop-72', 'coop', '72', 'Coop Rådhuset', '', 'Stockholm', 'Coop'),
('coop-60', 'coop', '60', 'Coop Örnsberg', '', 'Hägersten', 'Coop'),
('coop-2821', 'coop', '2821', 'Coop Centralhuset', '', 'Uppsala', 'Coop'),
('coop-3817', 'coop', '3817', 'Coop Sjöbo', '', 'Sjöbo', 'Coop'),
('coop-519', 'coop', '519', 'Coop Sveaplan Eskilstuna', '', 'Eskilstuna', 'Coop'),
('coop-3812', 'coop', '3812', 'Coop Dragonen', '', 'Ystad', 'Coop'),
('coop-41', 'coop', '41', 'Coop Råsundavägen', '', 'Solna', 'Coop'),
('coop-968', 'coop', '968', 'Coop Stenhamra', '', 'Stenhamra', 'Coop'),
('coop-205', 'coop', '205', 'Coop Öregrund', '', 'Öregrund', 'Coop'),
('coop-233', 'coop', '233', 'Coop Åby', '', 'Åby', 'Coop'),
('coop-1103', 'coop', '1103', 'Coop Åhus', '', 'Åhus', 'Coop'),
('coop-1045', 'coop', '1045', 'Coop Hyltebruk', '', 'Hyltebruk', 'Coop'),
('coop-52', 'coop', '52', 'Coop Brommaplan', '', 'Bromma', 'Coop'),
('coop-1771', 'coop', '1771', 'Coop Sala', '', 'Sala', 'Coop'),
('coop-3791', 'coop', '3791', 'Coop Svampen', '', 'Örebro', 'Coop'),
('coop-3838', 'coop', '3838', 'Coop Karolingatan', '', 'Malmö', 'Coop'),
('coop-3834', 'coop', '3834', 'Coop Kirseberg', '', 'Malmö', 'Coop'),
('coop-3484', 'coop', '3484', 'Coop Norra Djurgårdsstaden', '', 'Stockholm', 'Coop'),
('coop-235', 'coop', '235', 'Coop Saluhallen Norrköping', '', 'Norrköping', 'Coop'),
('coop-1065', 'coop', '1065', 'Coop Västervik', '', 'Västervik', 'Coop'),
('coop-3486', 'coop', '3486', 'Coop Röbäck', '', 'Röbäck', 'Coop'),
('coop-1108', 'coop', '1108', 'Coop Sibbhult', '', 'Sibbhult', 'Coop'),
('coop-531', 'coop', '531', 'Coop Malmköping', '', 'Malmköping', 'Coop'),
('coop-1576', 'coop', '1576', 'Coop Föraregatan', '', 'Kiruna', 'Coop'),
('coop-237', 'coop', '237', 'Coop Vadstena', '', 'Vadstena', 'Coop'),
('coop-3794', 'coop', '3794', 'Coop Fjugesta', '', 'Fjugesta', 'Coop'),
('coop-545', 'coop', '545', 'Coop Mariefred', '', 'Mariefred', 'Coop'),
('coop-3814', 'coop', '3814', 'Coop Skurup', '', 'Skurup', 'Coop'),
('coop-3841', 'coop', '3841', 'Coop Genarp', '', 'Genarp', 'Coop'),
('coop-3815', 'coop', '3815', 'Coop Bulltofta', '', 'Malmö', 'Coop'),
('coop-1577', 'coop', '1577', 'Coop Lappgatan', '', 'Kiruna', 'Coop'),
('coop-8', 'coop', '8', 'Coop Midsommarkransen', '', 'Hägersten', 'Coop'),
('coop-23', 'coop', '23', 'Coop Vaxholm', '', 'Vaxholm', 'Coop'),
('coop-2267', 'coop', '2267', 'Coop Tyresö Strand', '', 'Tyresö', 'Coop'),
('coop-234', 'coop', '234', 'Coop Trosa', '', 'Trosa', 'Coop'),
('coop-200', 'coop', '200', 'Coop Rimbo', '', 'Rimbo', 'Coop'),
('coop-1931', 'coop', '1931', 'Coop Gustavsberg', '', 'Gustavsberg', 'Coop'),
('coop-1115', 'coop', '1115', 'Coop Hörby', '', 'Hörby', 'Coop'),
('coop-181', 'coop', '181', 'Coop Kungsängen', '', 'Kungsängen', 'Coop'),
('coop-3492', 'coop', '3492', 'Coop Ånäset', '', 'Ånäset', 'Coop'),
('coop-76', 'coop', '76', 'Coop Bondegatan', '', 'Stockholm', 'Coop'),
('coop-1252', 'coop', '1252', 'Coop Vålberg', '', 'Vålberg', 'Coop')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, address = EXCLUDED.address, city = EXCLUDED.city, profile = EXCLUDED.profile;

-- Batch 7
INSERT INTO stores (id, chain_id, external_id, name, address, city, profile) VALUES
('coop-1100', 'coop', '1100', 'Coop Osby', '', 'Osby', 'Coop'),
('coop-1968', 'coop', '1968', 'Coop City Östersund', '', 'Östersund', 'Coop'),
('coop-1235', 'coop', '1235', 'Coop Munkfors', '', 'Munkfors', 'Coop'),
('coop-1563', 'coop', '1563', 'Coop Öjebyn', '', 'Öjebyn', 'Coop'),
('coop-106', 'coop', '106', 'Coop Djursholm', '', 'Djursholm', 'Coop'),
('coop-1566', 'coop', '1566', 'Coop Rosvik', '', 'Rosvik', 'Coop'),
('coop-80', 'coop', '80', 'Coop Odengatan', '', 'Stockholm', 'Coop'),
('coop-1906', 'coop', '1906', 'Coop Hammarby Sjöstad', '', 'Stockholm', 'Coop'),
('coop-517', 'coop', '517', 'Coop Östra Torget Torshälla', '', 'Torshälla', 'Coop'),
('coop-3776', 'coop', '3776', 'Coop Stjärnan Västerås', '', 'Västerås', 'Coop'),
('coop-11', 'coop', '11', 'Coop Kärrtorp', '', 'Johanneshov', 'Coop'),
('coop-55', 'coop', '55', 'Coop Finn Malmgren', '', 'Johanneshov', 'Coop'),
('coop-1471', 'coop', '1471', 'Coop Teg', '', 'Umeå', 'Coop'),
('coop-66', 'coop', '66', 'Coop Älta Gård', '', 'Älta', 'Coop'),
('coop-3493', 'coop', '3493', 'Coop Granlo', '', 'Sundsvall', 'Coop'),
('coop-79', 'coop', '79', 'Coop Storgatan', '', 'Stockholm', 'Coop'),
('coop-61', 'coop', '61', 'Coop Erik Dahlbergsgatan', '', 'Stockholm', 'Coop'),
('coop-62', 'coop', '62', 'Coop Garnisonen', '', 'Stockholm', 'Coop'),
('coop-512', 'coop', '512', 'Coop Kvarnen', '', 'Katrineholm', 'Coop'),
('coop-1919', 'coop', '1919', 'Coop Liljeholmen', '', 'Stockholm', 'Coop'),
('coop-2705', 'coop', '2705', 'Coop Folkparken', '', 'Södertälje', 'Coop'),
('coop-40', 'coop', '40', 'Coop Södra Station', '', 'Stockholm', 'Coop'),
('coop-165', 'coop', '165', 'Coop Rönninge', '', 'Rönninge', 'Coop'),
('coop-2801', 'coop', '2801', 'Coop Norrtull', '', 'Stockholm', 'Coop'),
('coop-238', 'coop', '238', 'Coop Lambohov', '', 'Linköping', 'Coop'),
('coop-3819', 'coop', '3819', 'Coop Oxie', '', 'Oxie', 'Coop'),
('coop-3770', 'coop', '3770', 'Coop Kungsör', '', 'Kungsör', 'Coop'),
('coop-1105', 'coop', '1105', 'Coop Sommarlust', '', 'Kristianstad', 'Coop'),
('coop-42', 'coop', '42', 'Coop Skarpnäck', '', 'Skarpnäck', 'Coop'),
('coop-3789', 'coop', '3789', 'Coop Nora', '', 'Nora', 'Coop'),
('coop-524', 'coop', '524', 'Coop Vingåker', '', 'Vingåker', 'Coop'),
('coop-2274', 'coop', '2274', 'Coop Engströms Livs', '', 'Bromma', 'Coop'),
('coop-69', 'coop', '69', 'Coop Gubbängen', '', 'Enskede', 'Coop'),
('coop-131', 'coop', '131', 'Coop Grindsgatan', '', 'Stockholm', 'Coop'),
('coop-3500', 'coop', '3500', 'Coop Brunne', '', 'Härnösand', 'Coop'),
('coop-3501', 'coop', '3501', 'Coop Tullporten', '', 'Härnösand', 'Coop'),
('coop-3502', 'coop', '3502', 'Coop Mariehem', '', 'Umeå', 'Coop'),
('coop-1479', 'coop', '1479', 'Coop Gunnarn', '', 'Gunnarn', 'Coop'),
('coop-1226', 'coop', '1226', 'Coop City Karlstad', '', 'Karlstad', 'Coop'),
('coop-1222', 'coop', '1222', 'Coop Dalsjöfors', '', 'Dalsjöfors', 'Coop'),
('coop-1508', 'coop', '1508', 'Coop Dikanäs', '', 'Dikanäs', 'Coop'),
('coop-625', 'coop', '625', 'Coop Skorped', '', 'Skorped', 'Coop'),
('coop-3505', 'coop', '3505', 'Coop Kvarnholmen', '', 'Nacka', 'Coop'),
('coop-3806', 'coop', '3806', 'Stora Coop Falkenberg', '', 'Falkenberg', 'Coop'),
('coop-57', 'coop', '57', 'Coop Minneberg', '', 'Bromma', 'Coop'),
('coop-3520', 'coop', '3520', 'Coop Haningeterrassen', '', 'Handen', 'Coop'),
('coop-3521', 'coop', '3521', 'Coop Alsike', '', 'Knivsta', 'Coop'),
('coop-3525', 'coop', '3525', 'Coop Ullånger', '', 'Ullånger', 'Coop'),
('coop-3531', 'coop', '3531', 'Coop Kongahälla', '', 'Kungälv', 'Coop'),
('coop-3533', 'coop', '3533', 'Coop Partille', '', 'Partille', 'Coop'),
('coop-3536', 'coop', '3536', 'Coop Varvet', '', 'Luleå', 'Coop'),
('coop-3830', 'coop', '3830', 'Coop Limhamn', '', 'Limhamn', 'Coop'),
('coop-3545', 'coop', '3545', 'Coop Norra Ringen', '', 'Piteå', 'Coop'),
('coop-3807', 'coop', '3807', 'Coop Slättenvägen', '', 'Falkenberg', 'Coop'),
('coop-3550', 'coop', '3550', 'Coop Mellerud', '', 'Mellerud', 'Coop'),
('coop-3743', 'coop', '3743', 'Coop Skövde Henriksbergsgatan Östermalm', '', 'Skövde', 'Coop'),
('coop-3557', 'coop', '3557', 'Coop Hjo', '', 'Hjo', 'Coop'),
('coop-3745', 'coop', '3745', 'Coop Lidköping Råda Mossevägen', '', 'Lidköping', 'Coop'),
('coop-3567', 'coop', '3567', 'Coop Borås Byttorp', '', 'Borås', 'Coop'),
('coop-3573', 'coop', '3573', 'Coop Mölndal Åby Katrinebergsgatan', '', 'Mölndal', 'Coop'),
('coop-3574', 'coop', '3574', 'Coop Skånegatan', '', 'Göteborg', 'Coop'),
('coop-3580', 'coop', '3580', 'Coop Göteborg Mölndalsvägen', '', 'Göteborg', 'Coop'),
('coop-3616', 'coop', '3616', 'Coop Kågeröd', '', 'Kågeröd', 'Coop'),
('coop-3617', 'coop', '3617', 'Coop Linden Motala', '', 'Motala', 'Coop'),
('coop-3874', 'coop', '3874', 'Coop Domino', '', 'Norrköping', 'Coop'),
('coop-3871', 'coop', '3871', 'Coop Stockholmsvägen', '', 'Norrköping', 'Coop'),
('coop-3868', 'coop', '3868', 'Coop Ullstämma', '', 'Linköping', 'Coop'),
('coop-3867', 'coop', '3867', 'Coop Drottninggatan Linköping', '', 'Linköping', 'Coop'),
('coop-3877', 'coop', '3877', 'Coop Eskilstunavägen Torshälla', '', 'Torshälla', 'Coop'),
('coop-3779', 'coop', '3779', 'Coop Köping', '', 'Köping', 'Coop'),
('coop-3796', 'coop', '3796', 'Coop Laxå', '', 'Laxå', 'Coop'),
('coop-3862', 'coop', '3862', 'Coop Mjölby', '', 'Mjölby', 'Coop'),
('coop-3649', 'coop', '3649', 'Coop Björna', '', 'Björna', 'Coop'),
('coop-3652', 'coop', '3652', 'Coop Staffanstorp', '', 'Staffanstorp', 'Coop'),
('coop-3653', 'coop', '3653', 'Coop Västra Hamnen', '', 'Malmö', 'Coop'),
('coop-3656', 'coop', '3656', 'Coop Vildgåsen Lund', '', 'Lund', 'Coop'),
('coop-3657', 'coop', '3657', 'Coop Bjärred', '', 'Bjärred', 'Coop'),
('coop-3688', 'coop', '3688', 'Coop Jönköping Anders Blomstrands Väg', '', 'Jönköping', 'Coop'),
('coop-3698', 'coop', '3698', 'Coop Borgholm', '', 'Borgholm', 'Coop'),
('coop-3699', 'coop', '3699', 'Coop Färjestaden Brofästet', '', 'Färjestaden', 'Coop'),
('coop-3706', 'coop', '3706', 'Coop Hagastaden', '', 'Stockholm', 'Coop'),
('coop-3709', 'coop', '3709', 'Coop Kök och Café', '', 'Karlstad', 'Coop'),
('coop-3720', 'coop', '3720', 'Coop Liljegatan', '', 'Uppsala', 'Coop'),
('coop-3721', 'coop', '3721', 'Coop Tullhuset', '', 'Gävle', 'Coop'),
('coop-3827', 'coop', '3827', 'Coop Stationsstaden', '', 'Kävlinge', 'Coop'),
('coop-3725', 'coop', '3725', 'Coop Odinsgatan', '', 'Göteborg', 'Coop'),
('coop-3718', 'coop', '3718', 'Coop Gamla Riksvägen', '', 'Kållered', 'Coop'),
('coop-3751', 'coop', '3751', 'Coop Bålsta', '', 'Bålsta', 'Coop'),
('coop-3804', 'coop', '3804', 'Coop Gallerian', '', 'Falkenberg', 'Coop'),
('coop-3809', 'coop', '3809', 'Coop Flygaregatan', '', 'Halmstad', 'Coop'),
('coop-3762', 'coop', '3762', 'Coop Ankarsrum', '', 'Ankarsrum', 'Coop'),
('coop-3828', 'coop', '3828', 'Coop Borstahusen', '', 'Landskrona', 'Coop'),
('coop-3765', 'coop', '3765', 'Coop Kolla Parkstad', '', 'Kungsbacka', 'Coop'),
('coop-3768', 'coop', '3768', 'Coop City Örnsköldsvik', '', 'Örnsköldsvik', 'Coop'),
('coop-3883', 'coop', '3883', 'Coop Mini Täby Park', '', 'Täby', 'Coop'),
('coop-3884', 'coop', '3884', 'Stora Coop Ronneby', '', 'Ronneby', 'Coop'),
('coop-3885', 'coop', '3885', 'Coop Kallkällan', '', 'Luleå', 'Coop'),
('coop-3886', 'coop', '3886', 'Stora Coop Norrböle', '', 'Skellefteå', 'Coop'),
('coop-3887', 'coop', '3887', 'Coop Kittelfjäll', '', 'Kittelfjäll', 'Coop'),
('coop-3888', 'coop', '3888', 'Coop Strömlida', '', 'Piteå', 'Coop')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, address = EXCLUDED.address, city = EXCLUDED.city, profile = EXCLUDED.profile;

-- Batch 8
INSERT INTO stores (id, chain_id, external_id, name, address, city, profile) VALUES
('coop-3889', 'coop', '3889', 'Coop Kiruna C', '', 'Kiruna', 'Coop'),
('coop-3890', 'coop', '3890', 'Coop Matboden', '', 'Nacka', 'Coop'),
('coop-165310', 'coop', '165310', 'Coop Tullholmen', '', 'Karlstad', 'Coop'),
('coop-186117', 'coop', '186117', 'Coop Oxbacken', '', 'Västerås', 'Coop'),
('coop-104210', 'coop', '104210', 'Stora Coop Svedala', '', 'Svedala', 'Coop'),
('coop-185091', 'coop', '185091', 'Coop Flen', '', 'Flen', 'Coop'),
('coop-185040', 'coop', '185040', 'Coop Katrineholm', '', 'Katrineholm', 'Coop'),
('coop-16993', 'coop', '16993', 'Coop Träkvista Alltid Öppet', '', 'Ekerö', 'Coop'),
('coop-196163', 'coop', '196163', 'Coop Lima', '', 'Lima', 'Coop'),
('coop-236220', 'coop', '236220', 'Coop City Skellefteå', '', 'Skellefteå', 'Coop'),
('coop-246650', 'coop', '246650', 'Coop Sävast', '', 'Boden', 'Coop'),
('coop-16992', 'coop', '16992', 'Coop Mini Haninge', '', 'Haninge', 'Coop'),
('coop-16991', 'coop', '16991', 'Coop Mini Gåvsta', '', 'Uppsala', 'Coop'),
('coop-186118', 'coop', '186118', 'Coop Punkt', '', 'Västerås', 'Coop'),
('coop-106530', 'coop', '106530', 'Coop Hjärup', '', 'Hjärup', 'Coop'),
('coop-123300', 'coop', '123300', 'Coop Öjersjö', '', 'Öjersjö', 'Coop'),
('coop-235970', 'coop', '235970', 'Coop Vemdalen', '', 'Vemdalen', 'Coop'),
('coop-16170', 'coop', '16170', 'Stora Coop Spånga', '', 'Spånga', 'Coop'),
('coop-236013', 'coop', '236013', 'Coop Östra Station', '', 'Umeå', 'Coop'),
('coop-55030', 'coop', '55030', 'Stora Coop Ingelsta', '', 'Norrköping', 'Coop'),
('coop-242900', 'coop', '242900', 'Coop Gällivare Centrum', '', 'Gällivare', 'Coop'),
('coop-15480', 'coop', '15480', 'Stora Coop Barkarby', '', 'Järfälla', 'Coop'),
('coop-126308', 'coop', '126308', 'Coop Backaplan', '', 'Göteborg', 'Coop'),
('coop-232400', 'coop', '232400', 'Stora Coop Avion', '', 'Umeå', 'Coop'),
('coop-245270', 'coop', '245270', 'Coop Arvidsjaur', '', 'Arvidsjaur', 'Coop')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, address = EXCLUDED.address, city = EXCLUDED.city, profile = EXCLUDED.profile;

-- Lidl national store
INSERT INTO stores (id, chain_id, external_id, name, address, city, profile) VALUES ('lidl-national', 'lidl', 'national', 'Lidl Sverige (alla butiker)', 'Nationella erbjudanden', 'Sverige', 'Nationell') ON CONFLICT (id) DO NOTHING;
